### ISSUE TITLE
New screenshot default file icons

### ISSUE THREAD

**Issue by will-stone** [will-stone/plastic#10]
Now using Material icons. Update docs site with a new screenshot.
Use Hack font and credit it.

**Comment by pkazmier** [comment]
We need to get you using Fira Code for your font now too :-)  I love the ligatures (see the => in the 2nd to last line of the screenshot).

<img width="1135" alt="screen shot 2018-03-05 at 8 24 39 pm" src="https://user-images.githubusercontent.com/747855/37010882-494bebd0-20b3-11e8-83c7-983e6d8174ff.png">

**Comment by will-stone** [comment]
I tried Fira for a while once but I didn’t like it; my brain is just now used to a non-ligature style of code. My font of choice at the moment is Hack.

**Comment by pkazmier** [comment]
I've not seen Hack before. I'll check it out. I had swapped to Fira Code when I was learning Rust as there is a lot of '::', '->', and '=>' going on the language, where I became fond of the ligatures.

**Comment by kayteh** [comment]
I also use Fira Code and Material Icons. To each their own, y'know.

**Comment by will-stone** [comment]
I'm gonna change the screenshot to use default icons (seti) as it's probably the most widely used and people should see what the theme looks like with it (I've gone back to using it too).

**Comment by will-stone** [comment]
Interesting. Unfortunately it adds a folder icon which shifts everything to the right. When horizontal space is at a premium (on a laptop, for example), I think it's good to not have the folder icons. Everyone to their own. Lots of people don't customise, so let's stick with the default for the new screenshot (when v2 is properly released), to give an unbiased view; as if someone was to download Code for the first time and install Plastic.

**Comment by will-stone** [comment]
Not using file icons any more (I just use the built-in Seti theme) so I'm going to close this.
