### ISSUE TITLE
Add link to Plastic variation on docs site

### ISSUE THREAD

**Issue by will-stone** [will-stone/plastic#11]
Plastic Slate by @kayteh is an awesome variation of Plastic. Add a link to it on the docs site.

**Comment by will-stone** [comment]
Include fork guidelines that outline what constitutes a “good” fork and able to be featured on the site.

**Comment by kayteh** [comment]
Maybe something like

- Keeps the overall general feel and simplicity of Plastic
- Prioritizes upstream changes over fork-specific changes, e.g. breaking upstream contribution guidelines
- Keeps reasonably up to date with upstream

**Comment by will-stone** [comment]
I like it! Everything will be subjective but hopefully we can refine them so that it covers off the general feel of the project. Let's iterate on your idea, here's my attempt, and I'm going to go with present tense for conciseness.

- Maintain the overall feel and simplicity of Plastic's style and configuration.
  - Group theme scopes by colour/style.
  - Avoid language-specific scopes where possible.
  - Keep to a 10-colour syntax palette.
- Stay, within reason, up-to-date with upstream changes.
  - When a new section of the UI has become theme-able, log an issue with Plastic first, then merge the changes into your fork.
  - Upstream takes precedent to any changes to meta items (e.g. this guideline).
- Your fork's identity conforms to the following:
  - Package name is prefixed with `plastic-`.
  - Theme name begins with "Plastic ".
  - Keep the same icon but update its colours (only). A fork that does not change syntax colours but only changes styles could swap some of the icon colours around, for example.

@kayteh we'll use Slate as the poster child of "a good fork" 😄

**Comment by will-stone** [comment]
I've just realised we can call these Plastic Forks 😆

**Comment by will-stone** [comment]
@kayteh Would you like to be the first to try the Plastic Fork system?

1. Pull my upstream changes.
2. `yarn`
3. Update `theme.yaml` with your colours.
4. `yarn build` - There's a test pack that will ensure your `theme.yaml` file is to spec.
5. That's it, you may want to clean-up any legacy bits and pieces.

**Comment by kayteh** [comment]
When I'm next able to, sure.
