### ISSUE TITLE
Research and try out new highlight backgrounds and borders

### ISSUE THREAD

**Issue by will-stone** [will-stone/plastic#13]
With Code 1.21 we have new highlight border options: https://code.visualstudio.com/updates/v1_21#_new-theme-colors-and-removal-of-old-colors

In Plastic v1.7.0, I added a cornflower blue border to word highlight. I'd like to improve the highlighting further. e.g. do we need background colours on words highlighted with a border, or maybe a different background colour?

I can refine this over time.

**Comment by will-stone** [comment]
This seems good so far:
```
"editor.wordHighlightBackground": "#00000000",
"editor.wordHighlightStrongBackground": "#00000000",
"editor.wordHighlightStrongBorder": "#D2D6db",
```

**Comment by pkazmier** [comment]
Word highlight? What am I missing? I tried double-clicking a word. I tried selecting multiple words with Apple-D. I tried searching for a word.

**Comment by will-stone** [comment]
Click a variable to see the borders.

**Comment by pkazmier** [comment]
I've never seen this before as the feature does not appear to work in Go or Python, and I don't use Javascript on a regular basis. I'll have to go figure out why as I really like it.

**Comment by pkazmier** [comment]
Instead of pure black, why not use your theme color `Woodsmoke #181A1F` which is darker than the background of the editor window, but still within the theme palette?

**Comment by will-stone** [comment]
Sorry, what is currently pure black?

**Comment by pkazmier** [comment]
Sorry, I should have been more clear. You had pasted this above:

```
"editor.wordHighlightBackground": "#00000000",
"editor.wordHighlightStrongBackground": "#00000000",
"editor.wordHighlightStrongBorder": "#D2D6db",
```

**Comment by will-stone** [comment]
That's fully transparent, not black.

**Comment by pkazmier** [comment]
Hmm ... let me show you what I see instead.

Here is what I see on my screen when I add the first of those 3 lines:
<img width="188" alt="screen shot 2018-03-10 at 10 38 24 am" src="https://user-images.githubusercontent.com/747855/37244479-4963844e-244f-11e8-8b3f-51c4365f15d9.png">

And here is what I see when I comment the line out:
<img width="192" alt="screen shot 2018-03-10 at 10 38 47 am" src="https://user-images.githubusercontent.com/747855/37244481-57076eee-244f-11e8-9fb7-be5ff9d9b1d7.png">

**Comment by pkazmier** [comment]
Weird, now I can't reproduce what I displayed above. I restarted my VSCode, so maybe it was in a funky state.
