### ISSUE TITLE
Enhancement: Alternate color for debugging

### ISSUE THREAD

**Issue by Tinathnath** [will-stone/plastic#136]
Hello !
I love the work you've done with Plastic.
I would however suggest an enhancement, could you add the support for "debugging mode" please ?
In standard VSC theme, when you start a debug session, the bottom bar becomes orange instead of blue. Would it be possible to have something similar with Plastic (not orange obviously 😃 ), because it's sometimes hard to tell if the debug session started or not.
Thank you !

**Comment by will-stone** [comment]
Hi 👋 Thank you for using Plastic.
It certainly does look possible: https://code.visualstudio.com/api/references/theme-color#status-bar-colors I'll have a play...

**Comment by will-stone** [comment]
What do you reckon?

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/654103/109062963-828d9200-76e0-11eb-8d93-c737a5d1110c.png">

**Comment by will-stone** [comment]
Or red:

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/654103/109063395-00519d80-76e1-11eb-933a-bfe1f3f1d3ef.png">

Or amber:

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/654103/109063584-3abb3a80-76e1-11eb-8418-fa32bc278123.png">

**Comment by Tinathnath** [comment]
That was quick !
Blue is the default primary color, and red is Plastic's primary so those might be confusing. I'd go for amber then 🤔

**Comment by will-stone** [comment]
Here's the rest of the Plastic colours...

Lavender?

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/654103/109129307-67ef0380-7748-11eb-8069-0c0d3c031174.png">

Fountain Blue?

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/654103/109129506-a08edd00-7748-11eb-96c3-75b78657c80b.png">

Harvest Gold?

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/654103/109129643-c3b98c80-7748-11eb-92ae-e7cdf9c7d6bb.png">

Olivine?

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/654103/109129729-ddf36a80-7748-11eb-93ea-7ddb4bc14b4c.png">

**Comment by Tinathnath** [comment]
I discussed it with colleagues, we like Amber and Lavender. Pick the one you prefer :)

**Comment by will-stone** [comment]
Well if the default is orange I feel it comes down to Whiskey (what I originally called "amber") and Harvest Gold. I think I'm going to go with Harvest Gold due to a better contrast ratio:

<img width="645" alt="image" src="https://user-images.githubusercontent.com/654103/109207832-7cabb580-77a1-11eb-986a-60a3f6e4e9c9.png">

<img width="614" alt="image" src="https://user-images.githubusercontent.com/654103/109207848-803f3c80-77a1-11eb-8625-8af87248f366.png">

Thanks for your help, I'll release shortly...

**Comment by Tinathnath** [comment]
Perfect ! Good point with the ratio you're right.
Thanks !
