### ISSUE TITLE
Missing syntax highlighting in properties files

### ISSUE THREAD

**Issue by ivancuric** [will-stone/plastic#16]
Plastic:
![image](https://user-images.githubusercontent.com/2827047/38174632-7949805e-35d0-11e8-86c6-b969df793c00.png)

Dark+:
![image](https://user-images.githubusercontent.com/2827047/38174640-9d2121d0-35d0-11e8-97f8-59010c17e43d.png)

**Comment by pkazmier** [comment]
I think the headings should remain in Sunglo (red), but we should change the left-hand side of the assignment to Cornflower (blue), as a file of all red can be eye jarring. To make that change, we just need a slightly more specific `keyword` scope as keywords are all Sunglo. I propose adding `entity.name.section.group-title` to Cornflower section. Will, do you agree?

**Comment by pkazmier** [comment]
Screenshot with Cornflower Blue used for the `keyword.other.definition` scope:
<img width="690" alt="screen shot 2018-04-01 at 6 20 45 pm" src="https://user-images.githubusercontent.com/747855/38178472-6aea5f66-35d9-11e8-902d-ef353d346652.png">

**Comment by will-stone** [comment]
Looks good to me. Want to PR it?

**Comment by pkazmier** [comment]
Sure, I'll submit it right now.

**Comment by pkazmier** [comment]
PR #17 submitted to resolve this issue.

**Comment by will-stone** [comment]
released in v1.10.0
