### ISSUE TITLE
VSCode Plastic Legacy v2 theme is now DEPRECATED, looking for maintainer

### ISSUE THREAD

**Issue by will-stone** [will-stone/plastic#168]
If you are reading this, you have probably seen the notice in the last release about the deprecation of the _Legacy v2_ theme. Please comment here if you'd like to publish and maintain the original Plastic theme, and I will help with the transition.

**Comment by hadialqattan** [comment]
Hi, I like the original Plastic Legacy v2 theme, I came here to be its maintainer to keep it alive!

+ I would say thanks for the awesome theme!

**Comment by will-stone** [comment]
Fantastic! I’ve got a fairly busy day today but I’ll try to get back to you tomorrow. In the meantime, If you don’t mind forking the repo (or start from scratch, I’ll leave that up to you) and setting me up as a contributor, that’d be great. Also please make sure you have a Microsoft dev account set up, so you can publish the theme.

**Comment by hadialqattan** [comment]
Nice, I prefer to transfer the repo instead of forking/initializing, so if you don't mind transferring it to me, that would be great!

technical steps: [Transferring a repository owned by your user account](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account).

more info: [About repository transfers](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#about-repository-transfers).

**Comment by hadialqattan** [comment]
Here is why I prefer that over forking: 
![image](https://user-images.githubusercontent.com/50833881/115149217-c612d580-a06b-11eb-86a9-9d8254864b2a.png)

**Comment by will-stone** [comment]
Huh?! Sorry, I think you misunderstood the request for a _v2 Legacy maintainer_. I'm not looking for someone to take over Plastic itself, just the old VSCode v2 Legacy theme.

**Comment by hadialqattan** [comment]
Oh, sorry, you're right, I'm gonna fork it right now! 😅

**Comment by hadialqattan** [comment]
@will-stone I've invited you, please check out your email 😅

**Comment by will-stone** [comment]
I am cleaning-up the fork now and will submit a PR to you soon 😄

**Comment by hadialqattan** [comment]
Hi, the `Plastic Legacy` has been published on the [marketplace](https://marketplace.visualstudio.com/items?itemName=HadiAlqattan.plastic-legacy).

**Comment by will-stone** [comment]
Nice one! I'll do a v7 release of VSCode Plastic that removes the legacy versions, and point people towards yours. Thank you for taking it on. Due to the mono-repo nature of Plastic, it may be hard for you track upstream but hopefully it's easy enough for you to just watch `themes/vscode/src/theme.ts` for changes when I do releases. I try to keep up with all the new theme-able items that VSCode release, but please feel free to nudge me if you see any UI bits which aren't in Plastic colours.
