### ISSUE TITLE
I used Microsoft's new Theme Converter to convert `Plastic` to a Visual Studio theme =)

### ISSUE THREAD

**Issue by GavinRay97** [will-stone/plastic#172]
Recently released:
- https://github.com/microsoft/theme-converter-for-vs

Unfortunately, the tokens don't look very good/map well to most languages that I can see =(
They look alright for C#.

Better than nothing maybe, hopefully the tool will improve as well.

[Plastic-Visual-Studio-Theme.zip](https://github.com/will-stone/plastic/files/7230266/Plastic-Visual-Studio-Theme.zip)

![plastic-vs1](https://user-images.githubusercontent.com/26604994/134784227-016e6002-f55d-449f-b8f8-f4b595e14206.png)
![plastic-vs2](https://user-images.githubusercontent.com/26604994/134784232-07d456ac-dccf-4fb9-8aa5-00a0bb7ae4b5.png)
![plastic-vs3](https://user-images.githubusercontent.com/26604994/134784237-15e5fc34-7862-4535-a4f8-c8da863b6f9a.png)

**Comment by will-stone** [comment]
Yeah they don't look great 😬 It's probably best to make it manually and match tokens: https://github.com/will-stone/plastic/blob/main/themes/vscode/src/theme.ts#L271

**Comment by GavinRay97** [comment]
Yeah, agreed.

Btw, I noticed this line in the code:
https://github.com/will-stone/plastic/blob/0e46eba7ed7d089e8605f096ee7daeb0d86fbc0b/themes/vscode/src/theme.ts#L32-L33

I took the contents of the JSON file produced by `Developer: Generate Color Theme From Current Settings` and put it into https://app.quicktype.io

Here you go 🙂 
https://gist.github.com/GavinRay97/241fd0797f223a2db0dc1114c2122a37

**Comment by will-stone** [comment]
Thanks @GavinRay97 However, it'd be great to have an official type so we know the `ThemeColors` keys are always up-to-date and it can be used to find missing keys.

**Comment by GavinRay97** [comment]
For sure -- if we can find the location of the JSON schema being referenced with `vscode://schemas/color-theme`, then we can generate TypeScript definitions from that.

**Comment by will-stone** [comment]
That certainly is complex. Thanks for doing the research. I'm going to close this as it looks like a Visual Studio theme would require manual building.
