### ISSUE TITLE
Shared bounty for community-contributed ports to other IDE's?

### ISSUE THREAD

**Issue by GavinRay97** [will-stone/plastic#173]
Not sure if anyone else would be interested, but I'd personally be willing to contribute ~$25-50 (based on effort/quality) for a Jetbrains IDE port. Maybe others also find themselves desperately longing for Plastic when using IE, IntelliJ or Visual Studio.

For me, doesn't even have to be perfect. Just "close enough" would be fine, and much better than nothing 😅 

Maybe the bounty gets high enough and it becomes worthwhile for someone to do it?

**Comment by barfurth** [comment]
I made an initial port to Jetbrains IDEs. Would need approval from @will-stone to publish a first version that can be worked off. I did implement basic colors for now and will need to add more languages. Java looks pretty sleep imo.

https://github.com/barfurth/plastic-jetbrains

**Comment by GavinRay97** [comment]
Hey, this is pretty slick!

Just installed it, looks great:

![idea64_MvxvI36ADJ](https://user-images.githubusercontent.com/26604994/145623675-20596178-250a-46ba-8422-70249e28e96d.png)

**Comment by barfurth** [comment]
Thanks for the feedback @GavinRay97, I'm all good without any donations. I hope you like the port! I will try to continue improving it, especially with more languages. I'm happy to accept any suggestions here or on the repository there.

If you want to donate something, pick a charity instead of me :)

**Comment by will-stone** [comment]
This is awesome. Are you happy for me to put this into the Plastic project but linked to your repo (as I don't have JetBrains and so won't be able to maintain it)?

**Comment by sbarfurth** [comment]
Thanks @will-stone, sure. I'm also not currently able to maintain it well, but I still have the relevant infrastructure. I guess it won't hurt to add it. Last time I checked it was still working well.

**Comment by will-stone** [comment]
Cheers @sbarfurth, I've added a [Community Themes](https://github.com/will-stone/plastic/blob/main/themes/community-themes.yml) file which is shown at the bottom of the homepage 😀

https://plastictheme.com/

**Comment by GavinRay97** [comment]
@sbarfurth It still works fantastic, even with the new Jetbrains Beta UI

I've manually editted the plugin manifest in the `.jar` with 7-zip to get it to run in the new Beta UI and it still looks great!
