### ISSUE TITLE
Sticky scroll header support

### ISSUE THREAD

**Issue by alumni** [will-stone/plastic#180]
Sticky scroll can be enabled with: 
```json
{
  "editor.experimental.stickyScroll.enabled": true
}
```

It would be nice if we had some better styling for the header, e.g.:
```json
{
  "editorStickyScroll.background": "#181a1f",
  "editorStickyScrollHover.background": "#272930"
}
```

See also: https://github.com/microsoft/vscode/issues/157185

**Comment by will-stone** [comment]
This will be in the next release 👍 🙂
