### ISSUE TITLE
New update appears to have broken class color.

### ISSUE THREAD

**Issue by RoenLie** [will-stone/plastic#186]
Previously the class color was a nice yellow gold color.
After the new update, they are now the same color as the class keyword, the extends keyword and the implements keyword.
This makes creating a class look a bit off.

Would be nice to get the old golden class color back.
Thanks!

**Comment by will-stone** [comment]
Hi, can you please provide a code example? Thanks.

**Comment by RoenLie** [comment]
7.6
![image](https://user-images.githubusercontent.com/52429191/209552269-4e17ebd3-aa91-4093-b918-ce87a46ef513.png)

7.5
![image](https://user-images.githubusercontent.com/52429191/209552341-3885a3c4-e370-45af-b62b-bb9c681d70ed.png)

**Comment by will-stone** [comment]
Rolled-back last update 👍

**Comment by ciriousjoker** [comment]
@RoenLie Since you wanted the old color back as well, here's how I did it: https://github.com/will-stone/plastic/issues/188#issuecomment-1366192265
