### ISSUE TITLE
Possibly reconsider the pink (or add a theme option/README guide to customizing)

### ISSUE THREAD

**Issue by GavinRay97** [will-stone/plastic#190]
I don't mean to be a choosey beggar, but the Pink on some languages can be a bit overwhelming visually 😅 

- Java
![image](https://user-images.githubusercontent.com/26604994/210281150-80a07be2-8135-4683-80bc-6eb1b93e1ab9.png)

- Kotlin
![image](https://user-images.githubusercontent.com/26604994/210281607-2e51ca85-fc99-446b-8cf9-b14dc204a39a.png)

There might be others, it doesn't look so bad in C/C++, Zig, or C# from what I've seen

**Comment by will-stone** [comment]
Hey. Thanks for using Plastic. I’m a JS/TS dev and have found the new colour has been working well. Could you please submit a PR with your suggested colour, and test it out for a while yourself, as I’m open to suggestions. The main objective was to separate storage keywords from class names. 👍

**Comment by GavinRay97** [comment]
Maybe a potential solution would be to use language selectors to override with the pink on a per-language basis for JS(X)/TS(X)?

I think it might have been a happy accident, but somehow Plastic has looked amazing in _every language_ I've used it with. And I experiment with a lot of languages. (I can tell from the comments in `vscode/src/theme.ts` that it was only made for web dev)

The way I look at it, it's more like "Your theme, that you happen to share with the world", so I'm happy to bugger off

**Comment by will-stone** [comment]
Ha! Thanks. Yeah that’s open source for you 😆 I’m trying my best to keep it language agnostic at the mo. The problem was Svelte components as they are classified as classes when semantic highlighting kicks in.

**Comment by will-stone** [comment]
@GavinRay97 You’ll be pleased to know I think I’ve decided to now revert this 😊 Not because I don’t like it, but because I have another experiment I’d like to try (which will be separate from main Plastic theme) and I may as well put Plastic back to the way it was.

**Comment by will-stone** [comment]
9.0.0 will revert the pink.

**Comment by moontrio** [comment]
> 

So happy my favorite theme comes back.
