### ISSUE TITLE
Remove JetBrains theme from community themes

### ISSUE THREAD

**Issue by widersky** [will-stone/plastic#192]
It's just unmaintained - doesn't work with latest IDE versions 🤷‍♂️

**Comment by will-stone** [comment]
@sbarfurth 🤷‍♂️

**Comment by sbarfurth** [comment]
Hey, I'm okay with removing it. Since I switched jobs I no longer use JetBrains IDEs and thus don't have incentive (or time) to maintain it. Sorry about that, wish I could have done more.

I archived the repository in case someone wants to use it as a starting point for a new version.

**Comment by will-stone** [comment]
Theme is no longer linked to.
