### ISSUE TITLE
Markdown theming

### ISSUE THREAD

**Issue by SpoonBytes** [will-stone/plastic#24]
With the latest update to `v2.0.0` it appears that the theming for Markdown has received a downgrade. In `v1.x.x`, colors were applied to bold and italic texts, but in `v2.0.0` that is no longer the case. Is this intentional? And if so, is there a way to get the old Markdown theming back?

Thanks!

**Comment by will-stone** [comment]
> downgrade
 
hmmmm. You got all this for free, be nice.

> v1.x.x applied colors to bold and italicized text

I've simplified the scoping. I don't see why bold and italic need be another colour, after all, this isn't how they are defined in rich text editors.

> is there a way to get the old Markdown theming back?

In Plastic, no. I want the scopes to be as simple as possible and I really don't see the benefit to colouring in bold and italic markdown text.
You are free to fork Plastic, however I ask that you respectfully change the name, logo, and website.

**Comment by SpoonBytes** [comment]
> hmmmm. You got all this for free, be nice.

I apologize if I came across as impolite or ungrateful - that wasn't my intent and I realize now that my word choice could have been better. Thank you for answering my questions.
