### ISSUE TITLE
Low contrast Git warning

### ISSUE THREAD

**Issue by slbls** [will-stone/plastic#25]
When typing a commit message, VS Code provides a warning if the user's message exceeds 72 characters. With `v2.0.0`'s updated colors and other adjustments (which have otherwise been great), this message has become more difficult to read (see below for an example). This is likely due to the background and text colors both being relatively light, causing the two to blend.

I am not familiar with the granularity of customization VS Code allows for its themes (and I know that Plastic is aiming to remain a relatively simple theme, per the `README`), but is it possible that the background color or text color could be adjusted here to increase contrast and legibility?

!["72 character limit exceeded" message](https://user-images.githubusercontent.com/6751958/40843007-9e00f6e8-657d-11e8-9770-f9d0c3463e42.png)

**Comment by will-stone** [comment]
That's not good. Thanks for spotting this. It seems like Dark+'s approach to this is to use the light yellow for borders but a darker one for backgrounds:
![image](https://user-images.githubusercontent.com/654103/40843097-d5e438ca-65a7-11e8-82b5-b52e466c3699.png)

As the foreground (the text) can't currently be styled for that box. Ok, I'll look into it. I want to make the config builder as simple as possible too and would rather not have to add an option for `warning_dark` or whatever. I'll have a play, maybe adding some trasparency to that background will work (it depends if there's a colour underneath it), or I could use the tinycolor2 package (that I'm using to check colours validate) to darken the chosen colour for warnings and errors for backgrounds. Either way, the fix should be easy enough. This may sound like waffle to you but I like to write down my thoughts here so I can check back when I come to do the work.

Cheers.

**Comment by bearinsun** [comment]
@will-stone just checking in—do you have any updates on the status of this? Is there anything I can do to help?

**Comment by will-stone** [comment]
Hi @bearinsun, I tend to cycle around my projects, moving on when I get bored. I'll be back to Plastic soon 🙂

**Comment by will-stone** [comment]
Ok, I've taken a look at this and it looks like the only way to currently solve the problem is to make the warning and error background colours darker. However, there are some new options coming soon that will allow me to set the text colour: https://github.com/Microsoft/vscode/pull/57734

I'd rather wait for that to go in (which looks like it will be the next release). Mainly because it allows me to keep the flat look I intended for.

**Comment by bearinsun** [comment]
@will-stone sounds good—glad to hear there's a plan. Thanks for keeping Plastic updated!
