### ISSUE TITLE
Remove borders

### ISSUE THREAD

**Issue by laugri** [will-stone/plastic#28]
Hi there,

First of all, I wanted to thank you for this very excellent theme. I have been using the deprioritized punctuation theme for several months now and I think it's the best overall theme for VS Code.

I don't know if you are open to design suggestions, but here is one that is borderline nitpicking.

Below are two screenshots, one with the Plastic theme and one with the Dark+ theme. Most popular themes likes Dark+ adopt a flatter design without borders around the tab title, and between the tab and side bar. What is your position on this? Is that something you would consider changing? Otherwise, would it be ok for me to fork and tune the theme?

![image](https://user-images.githubusercontent.com/7806174/46476965-bdc65800-c7e9-11e8-857d-5b8de1a02544.png)

![image](https://user-images.githubusercontent.com/7806174/46476932-a8e9c480-c7e9-11e8-9322-81053f042ddd.png)

**Comment by will-stone** [comment]
Hi. Thanks! 😄 
That's the [contrast](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_contrast-colors) setting. I quite like how it separates the different sections, and feel it's a core part of Plastic's look and feel now. However, of course you can tweak it.

I'm in the process of making a Plastic theme builder (it's basically finished, I just haven't documented it yet). I could include a contrast config flag that turns that on/off, however, I want to keep the theme config file as simple as possible, we'll see how I feel once it's finished and I've cranked-out a few Plastic variations (I'm calling them Plastic Forks 😆 ). In the meantime, this is the line you need: https://github.com/will-stone/plastic/blob/master/theme-builder/config.yaml#L83
Then run `yarn build-vscode` from the root of this repo.

**Comment by laugri** [comment]
Thanks a lot for the input ! :)

**Comment by will-stone** [comment]
@laugri The builder is now (mildly) documented: https://github.com/will-stone/plastic#development
