### ISSUE TITLE
Markdown headers no longer colored in v3.0.0

### ISSUE THREAD

**Issue by plul** [will-stone/plastic#42]
After the update to 3.0.0, Markdown headers are no longer colored.

**Comment by will-stone** [comment]
Hmmm... please read "For the user" section of: https://css-tricks.com/open-source-etiquette-guidebook/#article-header-id-1

That's `entity.name.section` scope. I'll add that in and see if it has any knock-on affect on the code syntax.

**Comment by plul** [comment]
Thank you. 

I like the color theme and I have used it with vscode for about 6 months I think. I too like what the 3.0.0 update made my python code look like. 

To clarify, I am creating this issue because I want to help you develop the project by making you aware of this issue. Not to express dissatisfaction that 3.0.0 broke my markdown syntax highlighting.

**Comment by will-stone** [comment]
Awesome! It's good to know it works with other languages (I mainly test with TS and JS).

**Comment by will-stone** [comment]
Fixed in 3.0.1. Thanks 😄

**Comment by plul** [comment]
Thanks! I can confirm that it works.

I used to write a lot of TS. Now I mainly write Rust, Python, Java and Markdown, and I like Plastic for all of those. :)

**Comment by will-stone** [comment]
Even better! If you'd like, you could add sample Rust and Java files to this project? That way I can keep an eye on the changes I make to the theme for more languages. https://github.com/will-stone/plastic/tree/master/samples

**Comment by plul** [comment]
Thanks, I might contribute some Rust sample when I have the time. 
I think the Python sample you have can be updated to Python 3 code, now that [Python 2 is dead](https://www.python.org/doc/sunset-python-2/) and possibly include support for [typing](https://docs.python.org/3/library/typing.html). Typing in Python 3 is much like TS is for JS.

**Comment by will-stone** [comment]
Okay, thanks. I just grabbed that from a repo somewhere.

I didn't realise Python had typing, maybe I'll have to take a look at Python again 🤔

**Comment by plul** [comment]
I would recommend it. 
Rust has a great type system. Typing in Python 3 feels like a band-aid just like TypeScript is a bit of a band-aid for applying typing to JavaScript. 
But I like TypeScript and I like Python 3 with typing. It is a million times nicer than no typing in my experience. In Python, the typing has no effect without a third party static type checker, so you need something like [mypy](http://mypy-lang.org/) to do type checking, like what TypeScript does before it outputs JavaScript.

**Comment by plul** [comment]
I updated the Python sample: #43
