### ISSUE TITLE
MagicPython support

### ISSUE THREAD

**Issue by leiserfg** [will-stone/plastic#6]
Add MagicPython support

**Comment by will-stone** [comment]
What isn't working? Are you providing a pull-request?

**Comment by leiserfg** [comment]
Your palette is awesome but I am using magic python and your theme does not supports some of the custom scopes that Magic Python introduces. Take a look at https://github.com/leido/unofficial-vscode-theme-chromodynamics

**Comment by will-stone** [comment]
It's not a language I use. Please provide a pull-request if you'd like it supported. This article is a good starting point: https://medium.com/@caludio/how-to-write-a-visual-studio-code-color-theme-from-scratch-7ccb7e5da2aa

**Comment by pkazmier** [comment]
MagicPython is the default syntax used by VSCode according to it's [documentation](https://github.com/MagicStack/MagicPython#magic-python----).

@leiserfg, Will did commit a PR of mine, which improved the Python support, but I worked under his guidelines, which clearly state the following:

> please keep in mind that this theme strives to remain simple and language agnostic; for example, please do not ask for blah.blah.php or blah.blah.c scopes to be added.

One could argue that it's not possible to remain simple and language agnostic as every language seems to have their own interpretation of each of the generic scopes. There really isn't much consistency, so it's very hard to create a theme tailored to one without impacting the other - unless, of course, you used language specific scopes.

With that said, could you be more specific in terms of which Python syntax you would like highlighted? Maybe I could take a quick stab at improving. Looking at the screenshot of that other theme you provide, the only missing piece that I could see is the use of a different color docstrings and strings. I also like how Plastic highlights method calls, which that screenshot did not do.

**Comment by leiserfg** [comment]
The most important syntax highlighting I miss is in regular expressions, look at this:

https://camo.githubusercontent.com/67d8c8fa28f03f13123e6d9a9b410e19a6c39f67/68747470733a2f2f6d61676963737461636b2e6769746875622e696f2f4d61676963507974686f6e2f6578616d706c652e706e67

**Comment by pkazmier** [comment]
I typed that regex from your screenshot into my VSCode, and it does look similar (obviously different colors):

<img width="845" alt="screen shot 2018-03-03 at 12 51 44 pm" src="https://user-images.githubusercontent.com/747855/36938068-cf47af2c-1ee1-11e8-9bb1-aa0773b0e414.png">

The key differences seem to be the unique scopes for the capturing and non-capturing parens and the escape characters. Is that it? I think I might be able to make some changes that would satisfy you while sticking to Will's constraints about x.x.x.python scopes.

**Comment by pkazmier** [comment]
Okay, how do you like this. I have made the following changes:

- Capturing and non-capturing parens are distinguished from regular text elements (Cornflower Blue)
- Elements such as \A and \Z are distinguished from regular text elements (Whiskey)
- Docstrings are now different color from regular string (Raven)

I made all three changes without impacting any of the other test languages: Javascript, Go, Python.

<img width="638" alt="screen shot 2018-03-03 at 2 09 49 pm" src="https://user-images.githubusercontent.com/747855/36938788-98fec4cc-1eec-11e8-94ae-cf3f325104ed.png">

If you like, I'll submit a PR to Will with the changes.

**Comment by leiserfg** [comment]
Coool
