### ISSUE TITLE
VSCode terminal colors?

### ISSUE THREAD

**Issue by pkazmier** [will-stone/plastic#8]
Will, do you use your Plastic color palette for the integrated terminal in VSCode? 

I have assigned the various colors from your theme to the terminal ANSI colors in my VSCode prefs. I think the result looks [good](https://github.com/pkazmier/bash-prompt#vscode-integrated-terminal).

Here is the mapping I used:

Plastic Color | ANS Terminal Color
------------ | -------------------
Shark | Black
Sunglo | Red
Olivine | Green
Harvest Gold | Yellow
Cornflower Blue | Blue
Whiskey | Magenta
Fountain Blue | Cyan
White | Cadet Blue
BrightBlack | Shuttle Gray
BrightWhite | Iron

For the rest of the "bright" versions, I just reused the non-bright color mapping. Should we include these in the theme as well? It seems like others would benefit and it tightly integrates the terminal with the rest of the theming you have done.

BTW, I also use roughly the same mapping for my MacOS Terminal.app as I can't get enough of this color palette. The same link above has a whole bunch of screenshots I made for a bash prompt I created.

**Comment by will-stone** [comment]
I use this theme for fish shell: https://github.com/will-stone/pure.fish
Happy to take a look at a pull-request; I never even thought about theming the terminal colours before as the theme I use for fish goes fairly well.

**Comment by pkazmier** [comment]
Before I go through that trouble, could you just add these lines to your prefs to see if you like them:

```
"workbench.colorCustomizations": {
        "terminal.ansiBlack": "#21252b" ,
        "terminal.ansiRed": "#e06c75",
        "terminal.ansiGreen": "#98c379",
        "terminal.ansiYellow": "#e5c07b",
        "terminal.ansiBlue": "#61afef",
        "terminal.ansiMagenta": "#d19a66",
        "terminal.ansiCyan": "#56b6c2",
        "terminal.ansiWhite": "#abb2bf",
        "terminal.ansiBrightBlack": "#5c6370",
        "terminal.ansiBrightRed": "#e06c75",
        "terminal.ansiBrightGreen": "#98c379",
        "terminal.ansiBrightYellow": "#e5c07b",
        "terminal.ansiBrightBlue": "#61afef",
        "terminal.ansiBrightMagenta": "#d19a66",
        "terminal.ansiBrightCyan": "#56b6c2",
        "terminal.ansiBrightWhite": "#d2d6db",
    },
```

**Comment by will-stone** [comment]
I like it! Thoughts so far:

- We need to make bright variations.
- Although not a current Plastic colour, we should have a true magenta; people will expect the colours to roughly match the names. Maybe we could use the one from OneDark as that is what this theme borrows heavily from.
- Lastly, should we be theming the terminal at all? This is just a discussion point. People may already have their favourite colours setup in their shell configs (like I did with fish), do we want to wipe that out and replace it with our colours? Even if it does look good :)

**Comment by will-stone** [comment]
This looks to be the correct hex for OneDark purple: #C678DD call it "lavender".

**Comment by pkazmier** [comment]
I agree with you. If we decide to theme the terminal, then we need the bright variants. As for a true magenta, although I did not mind Whiskey in my day-to-day use, I do like the magenta color you provided. It looks good. Regarding your last question about whether we should theme the terminal or not, I don't know. On the one hand, you have already themed more than just the editor, so why stop here? For me, I love the palette, and it bothers me every single time I see something that doesn't use it. On the other hand, if it has never bothered you, then I'm sure there are others in the same boat. 

Regardless of whether you decide to proceed or not, I would love to get the bright color variants from you, so I can complete my local settings. In addition, I would like to apply the bright variants to my terminal emulator (MacOS Terminal.app) as well. For the past several weeks, I've been using the same colors for the bright and non-bright versions. Now, I'll have to go back and update them to use the new magenta addition!

**Comment by will-stone** [comment]
<img width="288" alt="untitled pxm 2018-03-09 08-38-26" src="https://user-images.githubusercontent.com/654103/37198155-45ded3e4-2375-11e8-8cb3-1d1d571d40a2.png">

**Comment by will-stone** [comment]
As a note to myself: I used SASS's saturate function, by 10%, to obtain the bright colours.

**Comment by pkazmier** [comment]
Could you show a screenshot with a sentence in each non-bright color with a single word in the middle of that sentence using the bright color? It's hard to tell if there is enough of a difference to distinguish the two colors as they appear very similar (with exception of the white and black colors).

**Comment by will-stone** [comment]
I was looking for a way to do that in the terminal too. If you can find a way, please post it here.

**Comment by pkazmier** [comment]
I don't think many will be able to notice the subtle difference.

<img width="491" alt="screen shot 2018-03-09 at 7 08 53 am" src="https://user-images.githubusercontent.com/747855/37208919-d08dc7c8-2368-11e8-9820-f16fdb87d080.png">

**Comment by will-stone** [comment]
Can you please post that script? I'll make the bright colours brighter in next release.

**Comment by pkazmier** [comment]
```bash
$ for i in `seq 0 1 7`
> do
> c=$(tput setaf $i)
> b=$(tput setaf $(($i+8)))
> n=$(tput sgr0)
> echo ${c}The quick brown fox ${b}jumps${c} over the lazy dog ${n}
> done
```

**Comment by pkazmier** [comment]
Doh! I hadn't applied the colors yet to my terminal yet! Disregard that screenshot. I need to head to work, so I can post a new one tonight or you can just try running that bash script in your terminal to see how it looks. In any case, definitely ignore my screenshot until I get a chance to update the colors with the new ones. Sorry for confusion.

**Comment by pkazmier** [comment]
Here are two screenshots showing the new terminal color scheme applied. As we already acknowledged, more contrast is needed. 

*On a side note, the colors in my Terminal.app are undersaturated (validated via examining in Affinity Photo). I'll have to investigate why it is not using the specified colors. Maybe time to switch terminals, I keep hearing about alacrity ...*

### VSCode Terminal
<img width="502" alt="screen shot 2018-03-09 at 8 46 53 pm" src="https://user-images.githubusercontent.com/747855/37237606-1de61274-23db-11e8-8805-1ef802bb3e17.png">

### MacOS Terminal.app
<img width="489" alt="screen shot 2018-03-09 at 8 54 49 pm" src="https://user-images.githubusercontent.com/747855/37237677-6c2a47e2-23dc-11e8-843f-dc374c1ba147.png">

**Comment by pkazmier** [comment]
I think we also need to set the following:

```json
        "terminal.foreground": "#abb2bf",
```

This is the default foreground color used in the integrated terminal.

**Comment by will-stone** [comment]
Yes, good point. I can imagine "white" is the usual colour, which we've got covered, but I suppose this dealds with the exceptions.

**Comment by pkazmier** [comment]
Actually, the default color used in the terminal is the setting in `terminal.foreground`. The `ansiWhite` is only going to be used when a terminal specifically requests to be put in that color mode, `$(tput setaf 7)`, for example. For most people, the former will be the more common color they see.

**Comment by pkazmier** [comment]
Maybe it's just my eyes, but do you find it hard to read some of the saturated colors on the dark background. Here are is some random text colored using the colors from the theme:

<img width="594" alt="screen shot 2018-03-12 at 7 57 12 pm" src="https://user-images.githubusercontent.com/747855/37316943-fcd5788e-262f-11e8-9277-3ba0462d2295.png">

I tried a version of colors that were brighter, but less saturated. I think it improves readability. What do you think?

<img width="593" alt="screen shot 2018-03-12 at 7 57 52 pm" src="https://user-images.githubusercontent.com/747855/37316961-1ddcece2-2630-11e8-9e9c-83e644754f5c.png">

Here are the colors I used:

```json
        "terminal.ansiBrightRed": "#efb5ba",
        "terminal.ansiBrightGreen": "#cbe1bc",
        "terminal.ansiBrightYellow": "#f2dfbd",
        "terminal.ansiBrightBlue": "#b0d7f7",
        "terminal.ansiBrightMagenta": "#e2bbee",
        "terminal.ansiBrightCyan": "#aadae0",
        "terminal.ansiBrightBlack": "#5c6370",
        "terminal.ansiBrightWhite": "#d2d6db",
```

**Comment by will-stone** [comment]
I think I prefer the current implementation; the text seems more punchy, which is what I can imagine the bright variations are used for, i.e. in short bursts like bold or italic in prose.
